### ISSUE TITLE
"key" in postData causing conflict?

### ISSUE THREAD

**Issue by convertedmedia** [DoSomethingArchive/node-request-retry#5]
I get this error:

_tls_common.js:108
        c.context.setKey(options.key);
                  ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:108:19)
    at Object.exports.connect (_tls_wrap.js:859:21)
    at Agent.createConnection (https.js:82:14)
    at Agent.createSocket (_http_agent.js:194:16)
    at Agent.addRequest (_http_agent.js:166:23)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (/home/ubuntu/leads/node_modules/request/request.js:747:30)
    at Request.end (/home/ubuntu/leads/node_modules/request/request.js:1381:10)
    at end (/home/ubuntu/leads/node_modules/request/request.js:575:14)
    at Immediate._onImmediate (/home/ubuntu/leads/node_modules/request/request.js:589:7)
    at processImmediate [as _immediateCallback](timers.js:367:17)

I read on a forum that this can be caused by using the property "key" as part of the payload, which I am doing. Unfortunately I can't change this as I'm not in control of the API. This doesn't happen when I use request directly. Any ideas?

Many thanks.

**Comment by convertedmedia** [comment]
Fixed it. Passed requestRetry.post an object with properties uri and formData, seems to work fine now.
